name: rolltrack_frontend
description: A web app for RollTrack
version: 1.0.0
environment:
  sdk: ^3.0.0

dependencies:
  shelf: ^1.4.0
  shelf_static: ^1.1.0
  # Add your dependencies here
  # Example: http: ^1.0.0

dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.0

